import type { CurriculumPlan, Asset, Profile, DailyData } from './types'

export const MOCK_PROFILE: Profile = {
  id:                        'mock-user-id',
  email:                     'educator@lua.app',
  active_subscription_month: '2026-02',
  language_preference:       'en',
  is_admin:                  true,
  has_onboarded:             true,
  planning_cadence:          'monthly',
  age_group:                 '4-5'
}

export const MOCK_DAILY_DATA: DailyData = {
  philosophy: 'custom',
  theme:      'Galactic Gardens',
  month_year: '2026-02',
  days: [
    {
      date:       '2026-02-02',
      weekday:    'Monday',
      day_number: 1,
      domains: {
        sensory_layout: {
          title:     'Starlight Sensory Station',
          activity:  'Fill a large bin with black kinetic sand and hide star-shaped gems, moon rocks (smooth grey stones), and constellation cards inside. Place UV flashlights at the station to "discover" stars hiding in the dark sand.',
          materials: ['black kinetic sand', 'star-shaped gems', 'smooth grey stones', 'UV flashlights', 'constellation cards'],
          duration:  '25 minutes',
          en:        'Transform your sensory table into a corner of the cosmos. Children reach into the black sand galaxy to uncover sparkling stars and hidden planets, building tactile awareness and curiosity about the universe beyond our world.',
          pt:        'Transforme a mesa sensorial em um canto do cosmos. As crianças mergulham as mãos na areia galáctica para descobrir estrelas brilhantes e planetas escondidos, desenvolvendo a percepção tátil e a curiosidade sobre o universo.',
        },
        cognitive_literacy: {
          title:     'Planet Names Vocabulary Launch',
          activity:  'Create large illustrated planet cards (Sun, Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune). Practice sounding out the names, count syllables by clapping, and sort planets by size using printed circles.',
          materials: ['planet picture cards', 'syllable counting circles', 'size-sorting mats', 'crayons'],
          duration:  '20 minutes',
          en:        'Children explore eight new vocabulary words — our solar system planets — through picture cards, syllable clapping, and size sequencing. This builds phonological awareness while introducing early science concepts in a joyful, hands-on way.',
          pt:        'As crianças exploram oito novas palavras de vocabulário — os planetas do sistema solar — por meio de cartões ilustrados, palmas silábicas e sequenciamento por tamanho. Isso desenvolve a consciência fonológica enquanto apresenta conceitos científicos de forma lúdica.',
        },
        physical_outdoor: {
          title:     'Rocket Ship Blast-Off Run',
          activity:  'Outdoors, set up a "launchpad" (hula hoop) at one end of the yard. Children crouch inside it and on "3-2-1 Blast Off!" sprint to the other end (outer space). Play again as planets rotating slowly in orbit — arms wide, spinning gently in place.',
          materials: ['2 hula hoops', 'open outdoor space', 'cones for boundaries'],
          duration:  '20 minutes',
          en:        'Gross motor energy ignites as children become rockets blasting off and planets slowly orbiting. This high-movement activity develops speed, spatial awareness, and body coordination while reinforcing the concept of planets moving through space.',
          pt:        'A energia motora grossa se acende enquanto as crianças se tornam foguetes e planetas em órbita. Esta atividade de alto movimento desenvolve velocidade, consciência espacial e coordenação motora, reforçando o conceito de movimento planetário.',
        },
        social_emotional: {
          title:     'Mission Team Morning Meeting',
          activity:  'Gather in a circle as "Space Crew." Each child shares one thing they are excited to explore today using the sentence stem: "On my mission today, I hope to discover _______." Celebrate each response with a collective "Mission accepted!" and a thumbs up.',
          materials: ['circle seating', 'mission prompt card'],
          duration:  '15 minutes',
          en:        'Children practice active listening, turn-taking, and verbal expression in a low-stakes, joyful setting. The "mission" framing gives every child a sense of importance and belonging within the group, supporting self-confidence and community connection.',
          pt:        'As crianças praticam escuta ativa, espera de turno e expressão verbal em um ambiente lúdico e seguro. O enquadramento de "missão" dá a cada criança um senso de importância e pertencimento ao grupo, apoiando a autoconfiança.',
        },
        cultural_global: {
          title:     'Space Explorers Across the World',
          activity:  'Share photos and simple facts about astronauts from diverse countries: Mae Jemison (USA), Valentina Tereshkova (Russia), Yang Liwei (China), and Rakesh Sharma (India). Ask: "What do all explorers have in common?" Guide children to notice shared courage and curiosity.',
          materials: ['astronaut photo cards', 'world map poster', 'sticky dots for marking countries'],
          duration:  '15 minutes',
          en:        'Children discover that space exploration belongs to all of humanity. By meeting astronauts from different countries and backgrounds, they build an early understanding of global community and the universal human drive to explore and discover.',
          pt:        'As crianças descobrem que a exploração espacial pertence a toda a humanidade. Ao conhecer astronautas de diferentes países e origens, elas desenvolvem uma compreensão inicial da comunidade global e do impulso humano universal para explorar.',
        },
        parent_bridge: {
          title:     'Family Note — Week 1, Day 1',
          activity:  'Send home a brief summary of the day\'s Galactic Gardens theme launch, the planet vocabulary introduced, and the mission-team circle activity.',
          materials: [],
          duration:  '2 minutes',
          en:        'Today we launched our Galactic Gardens theme with a cosmos-inspired sensory station and explored planet names together! Ask your child: "Which planet did you like most and why?" This simple conversation reinforces vocabulary and shows them that school learning matters at home too.',
          pt:        'Hoje lançamos o tema Jardins Galácticos com uma estação sensorial inspirada no cosmos e exploramos os nomes dos planetas juntos! Pergunte ao seu filho: "Qual planeta você mais gostou e por quê?" Esta conversa simples reforça o vocabulário e mostra que o aprendizado escolar importa em casa também.',
        },
      },
    },
    {
      date:       '2026-02-03',
      weekday:    'Tuesday',
      day_number: 2,
      domains: {
        sensory_layout: {
          title:     'Moon Dough Craters',
          activity:  'Prepare moon dough (2 cups flour + ¼ cup oil, grey-tinted). Children use spoons, marbles, and small balls to create "meteor impact craters" in the dough. Place constellation printouts nearby for inspiration.',
          materials: ['moon dough (flour + oil)', 'grey food colouring', 'marbles', 'small balls', 'spoons', 'constellation prints'],
          duration:  '25 minutes',
          en:        'Moon dough gives children the resistance and texture of a real planetary surface to explore. Creating craters builds fine motor strength and introduces early geology concepts — how the surfaces of moons and planets are shaped by impacts from space.',
          pt:        'O "moon dough" oferece às crianças a resistência e textura de uma superfície planetária real para explorar. Criar crateras desenvolve a força motora fina e introduz conceitos iniciais de geologia — como as superfícies de luas e planetas são moldadas por impactos espaciais.',
        },
        cognitive_literacy: {
          title:     'Star Pattern Sequencing',
          activity:  'Provide star stickers and strips of black paper. Children create AB, ABC, and AABB repeating patterns with gold and silver star stickers. Extension: have them describe their pattern aloud ("gold, silver, gold, silver").',
          materials: ['black paper strips', 'gold star stickers', 'silver star stickers', 'pattern reference cards'],
          duration:  '20 minutes',
          en:        'Pattern recognition is a foundational math skill. Using star stickers on a "night sky" background makes the math feel like art. Children practice identifying, extending, and creating repeating patterns — a critical Pre-K math standard.',
          pt:        'O reconhecimento de padrões é uma habilidade matemática fundamental. Usar adesivos de estrelas em um fundo de "céu noturno" faz a matemática parecer arte. As crianças praticam identificar, estender e criar padrões repetitivos.',
        },
        physical_outdoor: {
          title:     'Meteor Shower Beanbag Toss',
          activity:  'Set up three hoops on the ground labelled "Moon," "Mars," and "Jupiter." Children toss beanbags (meteors) from increasing distances. Count how many "meteors" land on each planet. Encourage counting aloud.',
          materials: ['3 hula hoops', 'planet labels', 'beanbags', 'counting chart'],
          duration:  '20 minutes',
          en:        'This activity combines gross motor development with early numeracy. Children improve throwing coordination and aim while counting their "meteor landings," naturally integrating physical play with mathematical thinking in an exciting space context.',
          pt:        'Esta atividade combina desenvolvimento motor grosso com numeracia inicial. As crianças melhoram a coordenação e a pontaria ao contar seus "pousos de meteoritos", integrando naturalmente o jogo físico com o pensamento matemático.',
        },
        social_emotional: {
          title:     'Feelings on Other Planets',
          activity:  'Show illustrations of planets with simple facial expressions drawn on them. Ask: "If you lived on a planet made of ice, how might you feel? What about a planet covered in flowers?" Guide children to name emotions (curious, cozy, nervous, excited) and what might cause them.',
          materials: ['planet feeling cards', 'emotion word chart'],
          duration:  '15 minutes',
          en:        'By projecting emotions onto imaginary planetary scenarios, children practice naming a range of feelings without the vulnerability of personal disclosure. This playful distancing technique builds emotional vocabulary and empathy in a low-stakes, imaginative context.',
          pt:        'Ao projetar emoções em cenários planetários imaginários, as crianças praticam nomear uma variedade de sentimentos sem a vulnerabilidade da divulgação pessoal. Esta técnica lúdica desenvolve vocabulário emocional e empatia.',
        },
        cultural_global: {
          title:     'How Different Cultures See the Stars',
          activity:  'Show three different constellation stories: Greek (Orion the hunter), Aboriginal Australian (the Emu in the Sky), and Chinese (the Weaver Girl and Cowherd). Discuss how different people looked at the same stars and told different stories.',
          materials: ['constellation story cards', 'star projection if available'],
          duration:  '15 minutes',
          en:        'The same night sky has inspired thousands of different stories across human cultures. Children discover that there is no single "correct" way to see the stars — and that every culture has wisdom and imagination to share. A beautiful early lesson in perspective and respect.',
          pt:        'O mesmo céu noturno inspirou milhares de histórias diferentes entre as culturas humanas. As crianças descobrem que não existe uma única maneira "correta" de ver as estrelas — e que cada cultura tem sabedoria e imaginação para compartilhar.',
        },
        parent_bridge: {
          title:     'Family Note — Day 2',
          activity:  'Brief note about moon dough tactile play, star pattern math, and the multi-cultural constellation stories.',
          materials: [],
          duration:  '2 minutes',
          en:        'We made craters in moon dough and discovered that cultures around the world tell different stories about the same stars! Tonight, if the sky is clear, try stargazing together. Ask your child: "Can you make up your own constellation story?"',
          pt:        'Fizemos crateras em massa de lua e descobrimos que culturas ao redor do mundo contam histórias diferentes sobre as mesmas estrelas! Esta noite, se o céu estiver limpo, tentem observar as estrelas juntos. Pergunte ao seu filho: "Você consegue inventar sua própria história de constelação?"',
        },
      },
    },
    {
      date:       '2026-02-04',
      weekday:    'Wednesday',
      day_number: 3,
      domains: {
        sensory_layout: {
          title:     'Galaxy Slime Lab',
          activity:  'Set up a "laboratory" with clear slime mixed with blue, purple, and silver glitter. Children wear disposable gloves and use craft sticks to swirl galaxies. Place planet photos at the station for colour reference.',
          materials: ['clear slime base', 'blue & purple food colouring', 'silver glitter', 'craft sticks', 'disposable gloves', 'planet photos'],
          duration:  '25 minutes',
          en:        'Galaxy slime engages multiple senses simultaneously — sight (the swirling colours), touch (smooth and stretchy texture), and imagination. The open-ended nature of swirling galaxies encourages creativity while developing fine motor manipulation and hand strength.',
          pt:        'O slime galáctico envolve múltiplos sentidos simultaneamente — visão (as cores girando), toque (textura suave e elástica) e imaginação. A natureza aberta de criar galáxias estimula a criatividade enquanto desenvolve manipulação motora fina e força das mãos.',
        },
        cognitive_literacy: {
          title:     'Alien ABC Adventure',
          activity:  'Create simple "alien" character cards with names starting with each letter (Axlo, Bloop, Cryx…). Practice saying the letter sound, writing the capital letter in a sand tray, and drawing the alien. Focus on 5 letters per session.',
          materials: ['alien character cards (A–E)', 'sand trays', 'letter formation guides', 'drawing paper'],
          duration:  '20 minutes',
          en:        'Letter recognition and formation practice becomes a delightful creative adventure. Each alien character provides a memorable hook for each letter sound, leveraging narrative memory to support phonics learning in an engaging, non-pressured environment.',
          pt:        'A prática de reconhecimento e formação de letras se torna uma aventura criativa encantadora. Cada personagem alienígena fornece um gancho memorável para cada som de letra, aproveitando a memória narrativa para apoiar o aprendizado de fonética.',
        },
        physical_outdoor: {
          title:     'Zero Gravity Obstacle Walk',
          activity:  'Create an obstacle course with instructions: "Walk in SLOW MOTION through the asteroid field (pool noodles standing up), FLOAT across the moon surface (stepping stones), and JUMP to land on Mars (red mat)." Emphasise slow, controlled movements.',
          materials: ['pool noodles', 'stepping stones / carpet squares', 'red mat', 'instruction signs'],
          duration:  '20 minutes',
          en:        'Moving in slow motion and with deliberate control challenges children\'s body awareness and balance in an exciting new way. This activity builds proprioception, coordination, and the ability to regulate movement — all while imagining the thrill of zero gravity.',
          pt:        'Mover-se em câmera lenta e com controle deliberado desafia a consciência corporal e o equilíbrio das crianças de forma emocionante. Esta atividade desenvolve propriocepção, coordenação e a capacidade de regular o movimento — enquanto imagina a emoção de gravidade zero.',
        },
        social_emotional: {
          title:     'Astronaut Partner Problem-Solving',
          activity:  'In pairs, children are given a "mission challenge": move a ball from one hoop to another using only two pool noodles (no hands). They must talk, plan, and work together. Debrief: "What was hard? How did you help each other?"',
          materials: ['pool noodles', 'soft balls', 'hula hoops'],
          duration:  '20 minutes',
          en:        'This cooperative challenge requires children to communicate, negotiate roles, and persist through frustration — core social-emotional competencies. The astronaut framing elevates the task to a meaningful mission, increasing motivation and making collaboration feel purposeful.',
          pt:        'Este desafio cooperativo exige que as crianças se comuniquem, negociem funções e persistam através da frustração — competências socioemocionales fundamentais. O enquadramento de astronauta eleva a tarefa a uma missão significativa, aumentando a motivação.',
        },
        cultural_global: {
          title:     'International Space Station — Everyone is Welcome',
          activity:  'Show a simple infographic of the ISS and the countries that participate. Count the countries together (20+). Discuss: "The space station is a home where people from many countries live and work together. What rules might they need?" Chart responses.',
          materials: ['ISS country infographic', 'chart paper', 'markers'],
          duration:  '15 minutes',
          en:        'The International Space Station is one of humanity\'s greatest examples of global cooperation. Children discover that living together peacefully — even in the extraordinary environment of space — requires shared agreements, mutual respect, and kindness across cultural differences.',
          pt:        'A Estação Espacial Internacional é um dos maiores exemplos de cooperação global da humanidade. As crianças descobrem que viver juntos pacificamente — mesmo no ambiente extraordinário do espaço — requer acordos compartilhados, respeito mútuo e gentileza.',
        },
        parent_bridge: {
          title:     'Family Note — Day 3',
          activity:  'Note on galaxy slime sensory lab, astronaut partner problem-solving, and the ISS global cooperation discussion.',
          materials: [],
          duration:  '2 minutes',
          en:        'Midweek update from the Galactic Gardens! Today your child practiced teamwork by completing an astronaut mission with a partner. We also learned that the International Space Station has astronauts from 20+ countries living and working together. Ask: "What rules do you think they need to get along?"',
          pt:        'Atualização do meio da semana dos Jardins Galácticos! Hoje seu filho praticou o trabalho em equipe completando uma missão de astronauta com um parceiro. Também aprendemos que a Estação Espacial Internacional tem astronautas de mais de 20 países vivendo e trabalhando juntos.',
        },
      },
    },
    {
      date:       '2026-02-05',
      weekday:    'Thursday',
      day_number: 4,
      domains: {
        sensory_layout: {
          title:     'Cosmic Ice Excavation',
          activity:  'Freeze small plastic planets, stars, and gems in ice blocks overnight. Children use spray bottles (warm water), droppers, and wooden tools to excavate the treasures. Set on black trays with space music playing softly.',
          materials: ['ice blocks with frozen treasures', 'spray bottles', 'droppers', 'wooden craft sticks', 'black trays'],
          duration:  '30 minutes',
          en:        'Ice excavation is a richly engaging sensory experience that also builds scientific thinking — children observe how water temperature changes the ice (melting, dripping) and use persistence and tools strategically to reach their goal. A beautiful lesson in patience and cause-and-effect.',
          pt:        'A escavação de gelo é uma experiência sensorial ricamente envolvente que também desenvolve o pensamento científico — as crianças observam como a temperatura da água muda o gelo e usam ferramentas estrategicamente para atingir seu objetivo. Uma bela lição de paciência e causa-e-efeito.',
        },
        cognitive_literacy: {
          title:     'Space Journal — My Discoveries',
          activity:  'Give each child a simple folded "space journal" (3–4 pages). Today\'s prompt: draw and label (with support) one thing they\'ve discovered about space this week. Teacher circulates, acting as scribe for dictated captions.',
          materials: ['folded paper journals', 'crayons', 'pencils', 'star stickers for covers'],
          duration:  '20 minutes',
          en:        'Journaling integrates drawing (fine motor), oral language (dictation), and emerging literacy (labels and captions) in one meaningful activity. Children\'s space journals become a personalized record of learning — something they can share with pride and revisit with growing reading skills.',
          pt:        'O diário integra desenho (motor fino), linguagem oral (ditado) e literacia emergente (rótulos e legendas) em uma atividade significativa. Os diários espaciais das crianças se tornam um registro personalizado de aprendizagem — algo que podem compartilhar com orgulho.',
        },
        physical_outdoor: {
          title:     'Solar System Planet Walk',
          activity:  'Space planets at scale in the outdoor yard (scaled distances using a metre stick). Walk the "solar system," pausing at each planet marker to do a movement: Mercury = 5 fast steps, Saturn = spin with arms as rings, etc.',
          materials: ['planet name stakes / cards', 'metre stick for spacing', 'open outdoor space'],
          duration:  '20 minutes',
          en:        'Walking a scaled solar system gives children a felt sense of the vast distances in space while building cardiovascular endurance. The planet-specific movements deepen factual memory through the body — kinaesthetic learning at its most joyful and effective.',
          pt:        'Caminhar por um sistema solar em escala dá às crianças uma sensação dos vastos espaços no universo enquanto desenvolve resistência cardiovascular. Os movimentos específicos de cada planeta aprofundam a memória factual através do corpo — aprendizagem cinestésica em sua forma mais alegre.',
        },
        social_emotional: {
          title:     'Conflict on the Space Station',
          activity:  'Read aloud a short illustrated story about two astronauts who disagree about who gets the window seat. Stop before the resolution. Ask: "How do you think they felt? What could they do?" Co-create solutions as a class before revealing the book\'s ending.',
          materials: ['illustrated conflict story (or teacher-narrated)', 'solution chart paper'],
          duration:  '15 minutes',
          en:        'Using narrative to explore conflict gives children emotional and psychological distance, making it easier to problem-solve without defensiveness. Children practice perspective-taking, generating solutions, and evaluating outcomes — all essential conflict-resolution competencies.',
          pt:        'Usar narrativa para explorar conflitos dá às crianças distância emocional e psicológica, tornando mais fácil resolver problemas sem defensividade. As crianças praticam tomada de perspectiva, geração de soluções e avaliação de resultados.',
        },
        cultural_global: {
          title:     'World Space Day Celebrations',
          activity:  'Share that April 12 is "Yuri\'s Night" — celebrated by space enthusiasts worldwide to mark the first human spaceflight. Show photos of celebrations from different countries. Children design their own "Space Day" flag or banner.',
          materials: ['paper rectangles', 'crayons', 'markers', 'world celebration photos'],
          duration:  '15 minutes',
          en:        'Children discover that people across the globe celebrate scientific achievement together, creating a sense of global community around shared human milestones. Designing a personal flag develops creativity and invites children to imagine themselves as part of this worldwide celebration.',
          pt:        'As crianças descobrem que pessoas ao redor do mundo celebram conquistas científicas juntas, criando um senso de comunidade global em torno de marcos humanos compartilhados. Criar uma bandeira pessoal desenvolve a criatividade e convida as crianças a se imaginarem parte dessa celebração.',
        },
        parent_bridge: {
          title:     'Family Note — Day 4',
          activity:  'Note about the space journal, the scaled solar system walk, and the conflict-resolution story activity.',
          materials: [],
          duration:  '2 minutes',
          en:        'Your child started a personal Space Journal today — a beautiful record of their Galactic Gardens discoveries! We also walked a scaled solar system outside and practiced conflict resolution through storytelling. Ask to see their journal and listen to what they discovered this week!',
          pt:        'Seu filho começou um Diário Espacial pessoal hoje — um belo registro das descobertas dos Jardins Galácticos! Também caminhamos por um sistema solar em escala ao ar livre e praticamos resolução de conflitos através da narrativa. Peça para ver o diário e ouça o que eles descobriram esta semana!',
        },
      },
    },
    {
      date:       '2026-02-06',
      weekday:    'Friday',
      day_number: 5,
      domains: {
        sensory_layout: {
          title:     'Comet Tail Ribbon Wands',
          activity:  'Set up a creation station with paper rolls (comets) and strips of silver, blue, and white ribbons (tails). Children design and assemble their own comet wand. Then move to open space to wave them — watching trails of light.',
          materials: ['cardboard tubes', 'silver/blue/white ribbon strips', 'tape', 'open space for movement'],
          duration:  '20 minutes',
          en:        'The comet wand station blends fine motor construction (cutting, taping) with sensory-rich movement play. Watching the ribbon trails respond to movement builds an intuitive, embodied understanding of how comets leave trails through space as they travel through the solar system.',
          pt:        'A estação de varinha de cometa combina construção motora fina (cortar, colar) com jogo de movimento rico em sensações. Observar as faixas de fita respondendo ao movimento constrói uma compreensão intuitiva de como os cometas deixam rastros no espaço.',
        },
        cognitive_literacy: {
          title:     'Space Story Retell — Sequence the Mission',
          activity:  'After a week of space stories, give children 4 sequencing cards depicting: 1) planning the mission, 2) launching the rocket, 3) exploring space, 4) returning home. Children order them and retell the story to a partner.',
          materials: ['mission sequencing cards (4-panel)', 'story retell sentence starters'],
          duration:  '20 minutes',
          en:        'Story sequencing is a critical early literacy skill that builds narrative comprehension, logical reasoning, and oral language fluency. The mission context makes the sequence feel urgent and meaningful — children are motivated to get the order right to "complete the mission successfully."',
          pt:        'O sequenciamento de histórias é uma habilidade essencial de literacia inicial que desenvolve a compreensão narrativa, o raciocínio lógico e a fluência da linguagem oral. O contexto de missão torna a sequência urgente e significativa.',
        },
        physical_outdoor: {
          title:     'Galactic Gardens Celebration Movement',
          activity:  'End-of-week celebration movement routine: children choose their favourite space move (rocket blast-off, planet orbit, zero gravity float, comet dash). Play upbeat music and let children lead the group in their chosen moves.',
          materials: ['open space', 'upbeat music', 'comet wands from morning'],
          duration:  '20 minutes',
          en:        'Closing the week with child-led movement honours children\'s agency and celebrates their embodied learning. Choosing and leading their favourite move builds self-expression, confidence, and a joyful physical memory of the Galactic Gardens theme.',
          pt:        'Encerrar a semana com movimento liderado pela criança honra a agência das crianças e celebra seu aprendizado incorporado. Escolher e liderar seu movimento favorito desenvolve autoexpressão, confiança e uma memória física alegre do tema Jardins Galácticos.',
        },
        social_emotional: {
          title:     'Gratitude Galaxy — What I Appreciate About My Crew',
          activity:  'Each child receives a star cut-out. They draw or dictate one thing they appreciate about a classmate (assigned randomly). Stars are collected on a class "Gratitude Galaxy" display board. Read them aloud together.',
          materials: ['star cut-outs', 'crayons', 'display board', 'blu-tack'],
          duration:  '15 minutes',
          en:        'Practising gratitude and giving specific compliments are among the highest-impact social-emotional skills in early childhood. This activity closes the week on a warm, connected note — children feel seen and appreciated, and the class community is strengthened through genuine, peer-to-peer recognition.',
          pt:        'Praticar gratidão e dar elogios específicos estão entre as habilidades sociemocionais de maior impacto na primeira infância. Esta atividade fecha a semana com uma nota calorosa e conectada — as crianças se sentem vistas e apreciadas, e a comunidade da turma é fortalecida.',
        },
        cultural_global: {
          title:     'Dreams Without Borders — What Would YOU Explore?',
          activity:  'Show images of future missions: Mars colonies, space telescopes, and moon bases — featuring scientists from diverse backgrounds working together. Children draw "My Future Space Mission" and share one sentence about where they\'d go.',
          materials: ['future space mission images', 'drawing paper', 'crayons'],
          duration:  '15 minutes',
          en:        'Ending the week by inviting children to imagine their own future as explorers is a powerful act of identity affirmation. By seeing scientists and explorers who look like them from around the world, every child receives the implicit message: the universe is yours to explore.',
          pt:        'Encerrar a semana convidando as crianças a imaginar seu próprio futuro como exploradoras é um poderoso ato de afirmação de identidade. Ao ver cientistas e exploradores de todo o mundo, cada criança recebe a mensagem implícita: o universo é seu para explorar.',
        },
        parent_bridge: {
          title:     'Weekly Family Letter — Week 1 Complete',
          activity:  'Full week summary with suggestions for extending the Galactic Gardens theme at home over the weekend.',
          materials: [],
          duration:  '2 minutes',
          en:        'What a week in the Galactic Gardens! Your child explored planet names, made moon craters, practised teamwork on astronaut missions, and ended the week sharing gratitude with their classmates. This weekend: look up one real space fact together, or borrow a library book about space. The universe is theirs to explore! 🌿',
          pt:        'Que semana nos Jardins Galácticos! Seu filho explorou os nomes dos planetas, fez crateras na lua, praticou o trabalho em equipe em missões de astronauta e encerrou a semana compartilhando gratidão com os colegas. Neste fim de semana: pesquisem juntos um fato espacial real, ou peguem um livro de biblioteca sobre o espaço. O universo é deles para explorar! 🌿',
        },
      },
    },
  ],
}

export const MOCK_PLAN: CurriculumPlan = {
  id:           'mock-plan-preview',
  month_year:   '2026-02',
  theme_name:   'Galactic Gardens',
  daily_data:   MOCK_DAILY_DATA,
  is_published: true,
  created_at:   '2026-02-01T00:00:00Z',
}

export const MOCK_PLANS = [
  {
    id:           'mock-plan-preview',
    month_year:   '2026-02',
    theme_name:   'Galactic Gardens',
    is_published: true,
    created_at:   '2026-02-01T00:00:00Z',
  },
  {
    id:           'mock-plan-2',
    month_year:   '2026-01',
    theme_name:   'Enchanted Rainforest',
    is_published: true,
    created_at:   '2026-01-01T00:00:00Z',
  },
]

export const MOCK_ASSETS: Asset[] = [
  {
    id:         'asset-1',
    plan_id:    'mock-plan-preview',
    file_url:   '#',
    asset_type: 'Printable',
    title:      'Planet Names Flashcards — EN/PT',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id:         'asset-2',
    plan_id:    'mock-plan-preview',
    file_url:   '#',
    asset_type: 'Printable',
    title:      'Star Pattern Sequencing Worksheet',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id:         'asset-3',
    plan_id:    'mock-plan-preview',
    file_url:   '#',
    asset_type: 'Signage',
    title:      'Galactic Gardens Classroom Welcome Sign',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id:         'asset-4',
    plan_id:    'mock-plan-preview',
    file_url:   '#',
    asset_type: 'Signage',
    title:      'Mission Control Station Label Set',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id:         'asset-5',
    plan_id:    'mock-plan-preview',
    file_url:   '#',
    asset_type: 'Guide',
    title:      'Educator Guide — Galactic Gardens Full Month',
    created_at: '2026-02-01T00:00:00Z',
  },
]
